In [1]:
import pandas as pd
import numpy as np
import os
import glob
import datetime
from datetime import datetime

## Taking the sample of tweets from each day from the war beginning

The data is dowloaded from Kaggle (link below) and sample and taken from each day. Only the four days in December (18,19,20,21) are not available. In total, there are tweets from 130 days starting from 2022-08-19 to the 2023-01-01. Firstly, 800 of tweets are taken from each day, when only english language tweets are filtered. In total there are 52,353 tweets for sentiment analysis.

The sample is taken in local notebook, the data is saved as csv file and when uploaded to github.

https://www.kaggle.com/datasets/bwandowando/ukraine-russian-crisis-twitter-dataset-1-2-m-rows?select=UkraineWar

In [2]:
csv_files = glob.glob('*.{}'.format('csv'))
csv_files

['0905_UkraineCombinedTweetsDeduped.csv',
 '1224_UkraineCombinedTweetsDeduped.csv',
 '1213_UkraineCombinedTweetsDeduped.csv',
 '0822_UkraineCombinedTweetsDeduped.csv',
 '1122_UkraineCombinedTweetsDeduped.csv',
 '1115_UkraineCombinedTweetsDeduped.csv',
 '1005_UkraineCombinedTweetsDeduped.csv',
 '1001_UkraineCombinedTweetsDeduped.csv',
 '1029_UkraineCombinedTweetsDeduped.csv',
 '1126_UkraineCombinedTweetsDeduped.csv',
 '1111_UkraineCombinedTweetsDeduped.csv',
 '0929_UkraineCombinedTweetsDeduped.csv',
 '0826_UkraineCombinedTweetsDeduped.csv',
 '1217_UkraineCombinedTweetsDeduped.csv',
 '0901_UkraineCombinedTweetsDeduped.csv',
 '1208_UkraineCombinedTweetsDeduped.csv',
 '0921_UkraineCombinedTweetsDeduped.csv',
 '0916_UkraineCombinedTweetsDeduped.csv',
 '1228_UkraineCombinedTweetsDeduped.csv',
 '0819_UkraineCombinedTweetsDeduped.csv',
 '0831_UkraineCombinedTweetsDeduped.csv',
 '0909_UkraineCombinedTweetsDeduped.csv',
 '1106_UkraineCombinedTweetsDeduped.csv',
 '1009_UkraineCombinedTweetsDeduped.csv',
 '1016_UkraineCombinedTweetsDeduped.csv',
 '1119_UkraineCombinedTweetsDeduped.csv',
 '1021_UkraineCombinedTweetsDeduped.csv',
 '1012_UkraineCombinedTweetsDeduped.csv',
 '1025_UkraineCombinedTweetsDeduped.csv',
 '1102_UkraineCombinedTweetsDeduped.csv',
 '1204_UkraineCombinedTweetsDeduped.csv',
 '0925_UkraineCombinedTweetsDeduped.csv',
 '0912_UkraineCombinedTweetsDeduped.csv',
 '1203_UkraineCombinedTweetsDeduped.csv',
 '0922_UkraineCombinedTweetsDeduped.csv',
 '0915_UkraineCombinedTweetsDeduped.csv',
 '1022_UkraineCombinedTweetsDeduped.csv',
 '1105_UkraineCombinedTweetsDeduped.csv',
 '1101_UkraineCombinedTweetsDeduped.csv',
 '1011_UkraineCombinedTweetsDeduped.csv',
 '1129_UkraineCombinedTweetsDeduped.csv',
 '1026_UkraineCombinedTweetsDeduped.csv',
 '0829_UkraineCombinedTweetsDeduped.csv',
 '0926_UkraineCombinedTweetsDeduped.csv',
 '0911_UkraineCombinedTweetsDeduped.csv',
 '1207_UkraineCombinedTweetsDeduped.csv',
 '1230_UkraineCombinedTweetsDeduped.csv',
 '1227_UkraineCombinedTweetsDeduped.csv',
 '0919_UkraineCombinedTweetsDeduped.csv',
 '1210_UkraineCombinedTweetsDeduped.csv',
 '0821_UkraineCombinedTweetsDeduped.csv',
 '0906_UkraineCombinedTweetsDeduped.csv',
 '1031_UkraineCombinedTweetsDeduped.csv',
 '1006_UkraineCombinedTweetsDeduped.csv',
 '1109_UkraineCombinedTweetsDeduped.csv',
 '1121_UkraineCombinedTweetsDeduped.csv',
 '1116_UkraineCombinedTweetsDeduped.csv',
 '1019_UkraineCombinedTweetsDeduped.csv',
 '1125_UkraineCombinedTweetsDeduped.csv',
 '1112_UkraineCombinedTweetsDeduped.csv',
 '1002_UkraineCombinedTweetsDeduped.csv',
 '0902_UkraineCombinedTweetsDeduped.csv',
 '1223_UkraineCombinedTweetsDeduped.csv',
 '0825_UkraineCombinedTweetsDeduped.csv',
 '1214_UkraineCombinedTweetsDeduped.csv',
 '1024_UkraineCombinedTweetsDeduped.csv',
 '1013_UkraineCombinedTweetsDeduped.csv',
 '1103_UkraineCombinedTweetsDeduped.csv',
 '1205_UkraineCombinedTweetsDeduped.csv',
 '0913_UkraineCombinedTweetsDeduped.csv',
 '0924_UkraineCombinedTweetsDeduped.csv',
 '1229_UkraineCombinedTweetsDeduped.csv',
 '0917_UkraineCombinedTweetsDeduped.csv',
 '0920_UkraineCombinedTweetsDeduped.csv',
 '0908_UkraineCombinedTweetsDeduped.csv',
 '1201_UkraineCombinedTweetsDeduped.csv',
 '0830_UkraineCombinedTweetsDeduped.csv',
 '1130_UkraineCombinedTweetsDeduped.csv',
 '1008_UkraineCombinedTweetsDeduped.csv',
 '1107_UkraineCombinedTweetsDeduped.csv',
 '1020_UkraineCombinedTweetsDeduped.csv',
 '1118_UkraineCombinedTweetsDeduped.csv',
 '1017_UkraineCombinedTweetsDeduped.csv',
 '1110_UkraineCombinedTweetsDeduped.csv',
 '1127_UkraineCombinedTweetsDeduped.csv',
 '1028_UkraineCombinedTweetsDeduped.csv',
 '1216_UkraineCombinedTweetsDeduped.csv',
 '0827_UkraineCombinedTweetsDeduped.csv',
 '0928_UkraineCombinedTweetsDeduped.csv',
 '1209_UkraineCombinedTweetsDeduped.csv',
 '0904_UkraineCombinedTweetsDeduped.csv',
 '0823_UkraineCombinedTweetsDeduped.csv',
 '1212_UkraineCombinedTweetsDeduped.csv',
 '1225_UkraineCombinedTweetsDeduped.csv',
 '1114_UkraineCombinedTweetsDeduped.csv',
 '1123_UkraineCombinedTweetsDeduped.csv',
 '1004_UkraineCombinedTweetsDeduped.csv',
 '1113_UkraineCombinedTweetsDeduped.csv',
 '1124_UkraineCombinedTweetsDeduped.csv',
 '1003_UkraineCombinedTweetsDeduped.csv',
 '0903_UkraineCombinedTweetsDeduped.csv',
 '1215_UkraineCombinedTweetsDeduped.csv',
 '0824_UkraineCombinedTweetsDeduped.csv',
 '1222_UkraineCombinedTweetsDeduped.csv',
 '0820_UkraineCombinedTweetsDeduped.csv',
 '1211_UkraineCombinedTweetsDeduped.csv',
 '0918_UkraineCombinedTweetsDeduped.csv',
 '1226_UkraineCombinedTweetsDeduped.csv',
 '0930_UkraineCombinedTweetsDeduped.csv',
 '0907_UkraineCombinedTweetsDeduped.csv',
 '1108_UkraineCombinedTweetsDeduped.csv',
 '1007_UkraineCombinedTweetsDeduped.csv',
 '1030_UkraineCombinedTweetsDeduped.csv',
 '1018_UkraineCombinedTweetsDeduped.csv',
 '1117_UkraineCombinedTweetsDeduped.csv',
 '1120_UkraineCombinedTweetsDeduped.csv',
 '1027_UkraineCombinedTweetsDeduped.csv',
 '1128_UkraineCombinedTweetsDeduped.csv',
 '1010_UkraineCombinedTweetsDeduped.csv',
 '0910_UkraineCombinedTweetsDeduped.csv',
 '0927_UkraineCombinedTweetsDeduped.csv',
 '0828_UkraineCombinedTweetsDeduped.csv',
 '1231_UkraineCombinedTweetsDeduped.csv',
 '1206_UkraineCombinedTweetsDeduped.csv',
 '1202_UkraineCombinedTweetsDeduped.csv',
 '0914_UkraineCombinedTweetsDeduped.csv',
 '0923_UkraineCombinedTweetsDeduped.csv',
 '1023_UkraineCombinedTweetsDeduped.csv',
 '1014_UkraineCombinedTweetsDeduped.csv',
 '1104_UkraineCombinedTweetsDeduped.csv']

In [3]:
N = 800
df = pd.concat([pd.read_csv(f).sample(N) for f in csv_files], ignore_index=True)

/var/folders/gh/sp_gpz4x1q37l7xz154c85gh0000gn/T/ipykernel_33117/3908509912.py:2: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat([pd.read_csv(f).sample(N) for f in csv_files], ignore_index=True)

In [4]:
df

,Unnamed: 0,userid,username,acctdesc,location,following,followers,totaltweets,usercreatedts,tweetid,...,original_tweet_userid,original_tweet_username,in_reply_to_status_id,in_reply_to_user_id,in_reply_to_screen_name,is_quote_status,quoted_status_id,quoted_status_userid,quoted_status_username,extractedts
0,8023,1377229012544671746,xXOxygeNXx49,Nicey,Україна,11,1,121,2021-03-31 11:59:27.000000,1566688562082447361,...,0,NaN,1566594590563598336,800484748523028480,SupaIsaiah016,False,0,0,NaN,2022-09-05 17:06:25.009892
1,40431,3188934348,ZooTurkey,🥕vegetarisch🇧🇪Bxl→🇳🇱Ams→🇪🇸Bcn🍻西は天満、東は中目黒、北は🇨🇦ト...,~ lets do wat we shud do now ~,439,312,35181,2015-05-08 17:14:57.000000,1566892849513512961,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-09-06 01:32:03.101231
2,42042,84293339,Abraxas444,Retired UFO pilot,Earth,831,1179,7283,2009-10-22 10:29:59.000000,1566906265582055424,...,0,NaN,0,0,NaN,True,1566808856470007808,976284925769875456,Deus__Abscondis,2022-09-06 01:47:06.756572
3,14740,1112649747880468480,iwdu_global,Connecting women in politics globally | 80+ po...,"Washington, DC",433,520,196,2019-04-01 09:35:46.000000,1566734544039985152,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-09-05 12:23:43.377105
4,31186,1193230926773440512,ludilude1,"Être de gauche, cette maladie mentale",NaN,284,67,2208,2019-11-09 18:16:51.000000,1566833806644068355,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-09-06 00:46:53.206781
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103995,105854,939943152168980480,OneginRaul,Un simple mortal navegante de tempestades adqu...,AnywhereWorldwide.PlatanoPower,4179,193,8152,2017-12-10 19:41:25,1588649158432653312,...,0,NaN,1588571374637158400,611986351,KimDotcom,False,0,0,NaN,2022-11-05 01:58:17.525393
103996,67553,1567277468352151552,veknam62,"Google the ""Two Santa Claus Theory""",NaN,546,47,3503,2022-09-06 22:25:16,1588399326945910785,...,0,NaN,0,0,NaN,True,1585276465800572928,34713362,business,2022-11-04 20:40:05.503111
103997,71441,1061678161312866305,EdamDefense,@EdamOrg’s Security and Defense Studies Progra...,"Istanbul, Turkey",445,9498,2537,2018-11-11 17:52:53,1588436992949641216,...,0,NaN,0,0,NaN,True,1588283990137794560,256053751,JamestownTweets,2022-11-04 13:17:12.041615
103998,64072,38526413,Trust_In_Noto,Coastal Carolina Alum ‘10 University of South ...,NaN,446,93,2181,2009-05-07 21:52:56,1588352530375114752,...,0,NaN,0,138203134,AOC,True,1588344986906505216,264003515,SoFi,2022-11-04 04:05:11.786425
103999,62086,1384573120070045697,thestranger515,NaN,NaN,54,213,18700,2021-04-20 18:28:21,1588328973305778176,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-11-04 09:35:51.665873

In [5]:
for col in df.columns:
    print(col)

Unnamed: 0
userid
username
acctdesc
location
following
followers
totaltweets
usercreatedts
tweetid
tweetcreatedts
retweetcount
text
hashtags
language
coordinates
favorite_count
is_retweet
original_tweet_id
original_tweet_userid
original_tweet_username
in_reply_to_status_id
in_reply_to_user_id
in_reply_to_screen_name
is_quote_status
quoted_status_id
quoted_status_userid
quoted_status_username
extractedts

In [6]:
df_columns = df[['username', 'extractedts', 'text', 'language']]

In [7]:
df_columns.rename(columns = {'text':'tweet', 'extractedts':'created_at'}, inplace = True)

/var/folders/gh/sp_gpz4x1q37l7xz154c85gh0000gn/T/ipykernel_33117/2859154709.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_columns.rename(columns = {'text':'tweet', 'extractedts':'created_at'}, inplace = True)

In [8]:
df_columns

,username,created_at,tweet,language
0,xXOxygeNXx49,2022-09-05 17:06:25.009892,@SupaIsaiah016 Yummy,en
1,ZooTurkey,2022-09-06 01:32:03.101231,#報道ステーション\n\n#トラス首相 が誕生👍🏼✨✨✨\n\n#反プーチン\n\nロシア軍...,ja
2,Abraxas444,2022-09-06 01:47:06.756572,Peace is offensive concept for some of #Ukrain...,en
3,iwdu_global,2022-09-05 12:23:43.377105,Thanks to the @iwdu_global for another fruitfu...,en
4,ludilude1,2022-09-06 00:46:53.206781,"#Macron ça parle crise énergétique, électricit...",fr
...,...,...,...,...
103995,OneginRaul,2022-11-05 01:58:17.525393,@KimDotcom The only one that can supply cheap ...,en
103996,veknam62,2022-11-04 20:40:05.503111,#Ukraine #russia #RussiaIsLosing https://t.co/...,und
103997,EdamDefense,2022-11-04 13:17:12.041615,Savunma Programı Direktörümüz Dr. Can Kasapogl...,tr
103998,Trust_In_Noto,2022-11-04 04:05:11.786425,@AOC You know you want to support this. #Biden...,en
103999,thestranger515,2022-11-04 09:35:51.665873,#Russian commanders in #Kherson are fleeing &a...,en

In [9]:
df_columns.sort_values(by=['created_at'])

,username,created_at,tweet,language
15345,KYTKYTKYTKYTKYT,2022-08-19 04:42:04.913257,Η APU σκορπάει ορυχεία πετάλων σε κατοικημένες...,el
15553,W7VOA,2022-08-19 04:46:18.576534,From the ambassador of #China to the US: https...,en
15847,China2ASEAN,2022-08-19 05:41:50.778375,Chinese SC&amp;FM #WangYi said while holding a...,en
15347,FrDe2059,2022-08-19 05:41:52.515796,#China rewrites history of #coronavirus too. \...,en
15537,CGTNGlobalBiz,2022-08-19 05:41:56.697990,#Chinese FM makes proposal on building #China-...,en
...,...,...,...,...
97955,GED_Tweet,2023-01-01 01:55:04.435788,In 2022 #Russian war against #Ukraine &amp; t...,en
98226,Fraser1994,2023-01-01 01:55:05.276455,#Canada vs #Sweden New Years Eve. Please for t...,en
97991,GenevieGreer4,2023-01-01 01:55:05.310457,"~Longing to weaken 🇷🇺#Russia, 🇺🇸#USA👿 '#NATO-i...",en
98366,mogafilmstudio,2023-01-01 01:55:05.379121,🤵💍 Why do most men change after marriage?\n#ਜੱ...,en
98018,tekkned,2023-01-01 02:06:18.128144,@saintjavelin F#ck Russia #UkraineRussiaWar,in

In [10]:
df_columns["language"].value_counts()

en     52353
und    11412
uk      6341
de      6126
fr      4769
es      4438
it      4210
ru      2959
tr      1287
ja      1201
pt       744
in       697
nl       626
pl       625
ar       571
hi       510
zh       485
fa       412
el       381
fi       326
th       277
vi       248
ro       221
cs       193
et       189
sv       182
da       177
ur       177
ca       166
ht       142
tl       129
no       122
iw       119
eu       106
ko       104
ta       100
bn        94
lv        74
gu        69
bg        68
sr        68
te        65
lt        63
kn        59
sl        56
ka        48
is        48
cy        40
hu        29
mr        23
ml        19
pa        15
ne         9
ps         9
am         6
my         5
or         3
ckb        3
si         1
hy         1
Name: language, dtype: int64

In [11]:
#Leaving only english language tweets
df_columns = df_columns.query('language == "en"')

In [12]:
df_columns["language"].value_counts()

en    52353
Name: language, dtype: int64

In [13]:
df_columns['created_at'] = pd.to_datetime(df_columns['created_at']).dt.date

/var/folders/gh/sp_gpz4x1q37l7xz154c85gh0000gn/T/ipykernel_33117/1889624915.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_columns['created_at'] = pd.to_datetime(df_columns['created_at']).dt.date

In [14]:
df_columns.sort_values(by=['created_at'])

,username,created_at,tweet,language
15324,asicjk,2022-08-19,retrospective 099 April 30 russian sources #uk...,en
15905,Godson_Green,2022-08-19,Kwankwaso's Legacies.\n\n@KwankwasoRM for pres...,en
15432,TheTimDeFelice,2022-08-19,More of @brianstelter ‘s greatest hits #Russia...,en
15436,NasticInc,2022-08-19,🎥A Russian Helicopter shot down in Ukraine!!!!...,en
15437,puranik_shreyas,2022-08-19,Hire this awesome #Ukraine developer. And cre̖...,en
...,...,...,...,...
97781,mjjsmorenburg,2023-01-01,@reshetz And this why #fascist #Russia must be...,en
98134,sano_polo,2023-01-01,Happy new year! Hopefully this dream will be r...,en
98249,kashshka,2023-01-01,@CatherineBelton @HarperCollinsUK @ArabellaPik...,en
98276,benbvi3ws,2023-01-01,Roasted Russians: winter temperature raise and...,en
98361,MedakGunner,2023-01-01,@erinotoole Canadians have urgent reason to di...,en

In [17]:
df_columns['created_at'].value_counts()

2022-12-25    574
2022-12-29    516
2022-12-08    504
2022-10-28    484
2022-12-12    478
             ...
2022-08-19    289
2022-10-16    247
2022-12-18    125
2023-01-01    108
2022-10-15     91
Name: created_at, Length: 133, dtype: int64

In [18]:
df_columns.to_csv('russia_war_data_sample.csv')