In [1]:
import pandas as pd
import numpy as np
import os
import glob
import datetime
from datetime import datetime

## Taking the sample of tweets from each day from the war beginning

The data is dowloaded from Kaggle (link below) and sample and taken from each day. Only the four days in December (18,19,20,21) are not available. In total, there are tweets from 130 days starting from 2022-08-19 to the 2023-01-01. Firstly, 800 of tweets are taken from each day, when only english language tweets are filtered. In total there are 58,739 tweets for sentiment analysis.

The sample is taken in local notebook, the data is saved as csv file and when uploaded to github.

https://www.kaggle.com/datasets/bwandowando/ukraine-russian-crisis-twitter-dataset-1-2-m-rows?select=UkraineWar

In [5]:
csv_files = glob.glob('*.{}'.format('csv'))
csv_files

['0905_UkraineCombinedTweetsDeduped.csv',
 '1224_UkraineCombinedTweetsDeduped.csv',
 '1213_UkraineCombinedTweetsDeduped.csv',
 '0822_UkraineCombinedTweetsDeduped.csv',
 '1122_UkraineCombinedTweetsDeduped.csv',
 '1115_UkraineCombinedTweetsDeduped.csv',
 '1005_UkraineCombinedTweetsDeduped.csv',
 '1001_UkraineCombinedTweetsDeduped.csv',
 '1029_UkraineCombinedTweetsDeduped.csv',
 '1126_UkraineCombinedTweetsDeduped.csv',
 '1111_UkraineCombinedTweetsDeduped.csv',
 '0929_UkraineCombinedTweetsDeduped.csv',
 '0826_UkraineCombinedTweetsDeduped.csv',
 '1217_UkraineCombinedTweetsDeduped.csv',
 '0901_UkraineCombinedTweetsDeduped.csv',
 '1208_UkraineCombinedTweetsDeduped.csv',
 '0921_UkraineCombinedTweetsDeduped.csv',
 '0916_UkraineCombinedTweetsDeduped.csv',
 '1228_UkraineCombinedTweetsDeduped.csv',
 '0819_UkraineCombinedTweetsDeduped.csv',
 '0831_UkraineCombinedTweetsDeduped.csv',
 '0909_UkraineCombinedTweetsDeduped.csv',
 '1106_UkraineCombinedTweetsDeduped.csv',
 '1009_UkraineCombinedTweetsDeduped.csv',
 '1016_UkraineCombinedTweetsDeduped.csv',
 '1119_UkraineCombinedTweetsDeduped.csv',
 '1021_UkraineCombinedTweetsDeduped.csv',
 '1012_UkraineCombinedTweetsDeduped.csv',
 '1025_UkraineCombinedTweetsDeduped.csv',
 '1102_UkraineCombinedTweetsDeduped.csv',
 '1204_UkraineCombinedTweetsDeduped.csv',
 '0925_UkraineCombinedTweetsDeduped.csv',
 '0912_UkraineCombinedTweetsDeduped.csv',
 '1203_UkraineCombinedTweetsDeduped.csv',
 '0922_UkraineCombinedTweetsDeduped.csv',
 '0915_UkraineCombinedTweetsDeduped.csv',
 '1022_UkraineCombinedTweetsDeduped.csv',
 '1105_UkraineCombinedTweetsDeduped.csv',
 '1101_UkraineCombinedTweetsDeduped.csv',
 '1011_UkraineCombinedTweetsDeduped.csv',
 '1129_UkraineCombinedTweetsDeduped.csv',
 '1026_UkraineCombinedTweetsDeduped.csv',
 '0829_UkraineCombinedTweetsDeduped.csv',
 '0926_UkraineCombinedTweetsDeduped.csv',
 '0911_UkraineCombinedTweetsDeduped.csv',
 '1207_UkraineCombinedTweetsDeduped.csv',
 '1230_UkraineCombinedTweetsDeduped.csv',
 '1227_UkraineCombinedTweetsDeduped.csv',
 '0919_UkraineCombinedTweetsDeduped.csv',
 '1210_UkraineCombinedTweetsDeduped.csv',
 '0821_UkraineCombinedTweetsDeduped.csv',
 '0906_UkraineCombinedTweetsDeduped.csv',
 '1031_UkraineCombinedTweetsDeduped.csv',
 '1006_UkraineCombinedTweetsDeduped.csv',
 '1109_UkraineCombinedTweetsDeduped.csv',
 '1121_UkraineCombinedTweetsDeduped.csv',
 '1116_UkraineCombinedTweetsDeduped.csv',
 '1019_UkraineCombinedTweetsDeduped.csv',
 '1125_UkraineCombinedTweetsDeduped.csv',
 '1112_UkraineCombinedTweetsDeduped.csv',
 '1002_UkraineCombinedTweetsDeduped.csv',
 '0902_UkraineCombinedTweetsDeduped.csv',
 '1223_UkraineCombinedTweetsDeduped.csv',
 '0825_UkraineCombinedTweetsDeduped.csv',
 '1214_UkraineCombinedTweetsDeduped.csv',
 '1024_UkraineCombinedTweetsDeduped.csv',
 '1013_UkraineCombinedTweetsDeduped.csv',
 '1103_UkraineCombinedTweetsDeduped.csv',
 '1205_UkraineCombinedTweetsDeduped.csv',
 '0913_UkraineCombinedTweetsDeduped.csv',
 '0924_UkraineCombinedTweetsDeduped.csv',
 '1229_UkraineCombinedTweetsDeduped.csv',
 '0917_UkraineCombinedTweetsDeduped.csv',
 '0920_UkraineCombinedTweetsDeduped.csv',
 '0908_UkraineCombinedTweetsDeduped.csv',
 '1201_UkraineCombinedTweetsDeduped.csv',
 '0830_UkraineCombinedTweetsDeduped.csv',
 '1130_UkraineCombinedTweetsDeduped.csv',
 '1008_UkraineCombinedTweetsDeduped.csv',
 '1107_UkraineCombinedTweetsDeduped.csv',
 '1020_UkraineCombinedTweetsDeduped.csv',
 '1118_UkraineCombinedTweetsDeduped.csv',
 '1017_UkraineCombinedTweetsDeduped.csv',
 '1110_UkraineCombinedTweetsDeduped.csv',
 '1127_UkraineCombinedTweetsDeduped.csv',
 '1028_UkraineCombinedTweetsDeduped.csv',
 '1216_UkraineCombinedTweetsDeduped.csv',
 '0827_UkraineCombinedTweetsDeduped.csv',
 '0928_UkraineCombinedTweetsDeduped.csv',
 '1209_UkraineCombinedTweetsDeduped.csv',
 '0904_UkraineCombinedTweetsDeduped.csv',
 '0823_UkraineCombinedTweetsDeduped.csv',
 '1212_UkraineCombinedTweetsDeduped.csv',
 '1225_UkraineCombinedTweetsDeduped.csv',
 '1114_UkraineCombinedTweetsDeduped.csv',
 '1123_UkraineCombinedTweetsDeduped.csv',
 '1004_UkraineCombinedTweetsDeduped.csv',
 '1113_UkraineCombinedTweetsDeduped.csv',
 '1124_UkraineCombinedTweetsDeduped.csv',
 '1003_UkraineCombinedTweetsDeduped.csv',
 '0903_UkraineCombinedTweetsDeduped.csv',
 '1215_UkraineCombinedTweetsDeduped.csv',
 '0824_UkraineCombinedTweetsDeduped.csv',
 '1222_UkraineCombinedTweetsDeduped.csv',
 '0820_UkraineCombinedTweetsDeduped.csv',
 '1211_UkraineCombinedTweetsDeduped.csv',
 '0918_UkraineCombinedTweetsDeduped.csv',
 '1226_UkraineCombinedTweetsDeduped.csv',
 '0930_UkraineCombinedTweetsDeduped.csv',
 '0907_UkraineCombinedTweetsDeduped.csv',
 '1108_UkraineCombinedTweetsDeduped.csv',
 '1007_UkraineCombinedTweetsDeduped.csv',
 '1030_UkraineCombinedTweetsDeduped.csv',
 '1018_UkraineCombinedTweetsDeduped.csv',
 '1117_UkraineCombinedTweetsDeduped.csv',
 '1120_UkraineCombinedTweetsDeduped.csv',
 '1027_UkraineCombinedTweetsDeduped.csv',
 '1128_UkraineCombinedTweetsDeduped.csv',
 '1010_UkraineCombinedTweetsDeduped.csv',
 '0910_UkraineCombinedTweetsDeduped.csv',
 '0927_UkraineCombinedTweetsDeduped.csv',
 '0828_UkraineCombinedTweetsDeduped.csv',
 '1231_UkraineCombinedTweetsDeduped.csv',
 '1206_UkraineCombinedTweetsDeduped.csv',
 '1202_UkraineCombinedTweetsDeduped.csv',
 '0914_UkraineCombinedTweetsDeduped.csv',
 '0923_UkraineCombinedTweetsDeduped.csv',
 '1023_UkraineCombinedTweetsDeduped.csv',
 '1014_UkraineCombinedTweetsDeduped.csv',
 '1104_UkraineCombinedTweetsDeduped.csv']

In [6]:
N = 800
df = pd.concat([pd.read_csv(f).sample(N) for f in csv_files], ignore_index=True)

/var/folders/gh/sp_gpz4x1q37l7xz154c85gh0000gn/T/ipykernel_28133/3908509912.py:2: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat([pd.read_csv(f).sample(N) for f in csv_files], ignore_index=True)

In [7]:
df

,Unnamed: 0,userid,username,acctdesc,location,following,followers,totaltweets,usercreatedts,tweetid,...,original_tweet_userid,original_tweet_username,in_reply_to_status_id,in_reply_to_user_id,in_reply_to_screen_name,is_quote_status,quoted_status_id,quoted_status_userid,quoted_status_username,extractedts
0,39760,962696817702993921,TatjanaE1,I'm Russian speaking Ukrainian and I have supe...,Україна,177,27,5348,2018-02-11 14:36:22.000000,1566888341659963399,...,0,NaN,1566825411291537408,17469289,nypost,False,0,0,NaN,2022-09-06 01:02:56.440944
1,27166,1520043121949777920,peony_guy,"твої подруги скажуть, що я класний.",NaN,137,673,1643,2022-04-29 14:12:30.000000,1566809998935658497,...,0,NaN,1566809819297849344,311917242,grbzbhdn,False,0,0,NaN,2022-09-06 01:15:48.912323
2,7243,1102047326,mil_in_ua,"Чесно про армію, війну та оборонку з 2009 року",Київ,317,61543,24291,2013-01-18 21:18:11.000000,1566683425641304065,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-09-05 14:03:14.121065
3,31603,2226399648,conucrania,Asociación apolítica y sin ánimo de lucro. Apo...,España,488,2814,24216,2013-12-02 09:40:55.000000,1566836365249187843,...,0,NaN,0,0,NaN,True,1566764233576120320,934810674450059264,Militarylandnet,2022-09-06 01:04:35.088498
4,24353,2543569687,UKRinNewYork,Consulate General of Ukraine in New York / Ген...,"240 E 49St, New York, NY 10017",152,1798,9632,2014-06-03 13:46:37.000000,1566794036626743297,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-09-05 16:54:34.268519
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103995,100108,811742717474705412,CDMSoftwareHou,Global Logistics & Supply Chain Technology Sof...,Houston ∙ Los Angeles ∙ Miami,0,7,214,2016-12-22 01:18:40,1588610832262389760,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-11-05 00:47:36.297277
103996,84151,2890528054,Energy4Europe,We are the @EU_Commission’s Directorate-Genera...,Europe,796,58142,9219,2014-11-24 09:28:57,1588519191467855873,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-11-04 15:45:45.342452
103997,90257,734300346118463488,we_r8,Join us and give your opinion. Wer8™ or We.Rat...,United Kingdom,23,509,28977,2016-05-22 08:30:19,1588553254883000320,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-11-04 16:20:45.428383
103998,109264,1584842092261539840,LichtGrijs,"'1984' was a warning by George Orwell,\nnot a ...","Rotterdam, Nederland",64,21,480,2022-10-25 09:40:11,1588678212674293761,...,0,NaN,1588569086770176000,922457956574253056,DefensieMin,False,0,0,NaN,2022-11-05 02:06:21.195481
103999,107089,206257884,ian_hardacre,My passions are seeing more of the the world t...,Berkshire UK,21261,26155,54702,2010-10-22 15:58:29,1588658099954630659,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-11-05 00:32:36.390097

In [8]:
for col in df.columns:
    print(col)

Unnamed: 0
userid
username
acctdesc
location
following
followers
totaltweets
usercreatedts
tweetid
tweetcreatedts
retweetcount
text
hashtags
language
coordinates
favorite_count
is_retweet
original_tweet_id
original_tweet_userid
original_tweet_username
in_reply_to_status_id
in_reply_to_user_id
in_reply_to_screen_name
is_quote_status
quoted_status_id
quoted_status_userid
quoted_status_username
extractedts

In [9]:
df_columns = df[['username', 'extractedts', 'text', 'language']]

In [10]:
df_columns.rename(columns = {'text':'tweet', 'extractedts':'created_at'}, inplace = True)

/var/folders/gh/sp_gpz4x1q37l7xz154c85gh0000gn/T/ipykernel_28133/2859154709.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_columns.rename(columns = {'text':'tweet', 'extractedts':'created_at'}, inplace = True)

In [11]:
df_columns

,username,created_at,tweet,language
0,TatjanaE1,2022-09-06 01:02:56.440944,@nypost @OksanaLviv2 #Russians want #Ukrainian...,en
1,peony_guy,2022-09-06 01:15:48.912323,@grbzbhdn https://t.co/p3ugegDfjJ,und
2,mil_in_ua,2022-09-05 14:03:14.121065,Російські загарбники втратили декілька бойових...,uk
3,conucrania,2022-09-06 01:04:35.088498,Siguen llegando más y más imágenes de posicion...,es
4,UKRinNewYork,2022-09-05 16:54:34.268519,❗️#Ukraine’s grain exports have been suspended...,en
...,...,...,...,...
103995,CDMSoftwareHou,2022-11-05 00:47:36.297277,CDM Asset Tracking™ RFID Benefits\nhttps://t.c...,en
103996,Energy4Europe,2022-11-04 15:45:45.342452,📅22-23 November in Brussels🇧🇪 and online\n\nJo...,en
103997,we_r8,2022-11-04 16:20:45.428383,Q&amp;A: Chase CIO offers top interview tips f...,en
103998,LichtGrijs,2022-11-05 02:06:21.195481,@DefensieMin @oleksiireznikov @DefensieMin wil...,nl
103999,ian_hardacre,2022-11-05 00:32:36.390097,Hidden eyes and faces\n.\nAbstract from a refl...,en

In [12]:
df_columns.sort_values(by=['created_at'])

,username,created_at,tweet,language
15271,SphereByMilan,2022-08-19 04:42:03.079931,Look at this wonderful #Crimea sunset #HIMARSo...,en
15815,CE_ChinaEconomy,2022-08-19 04:46:19.075077,"A source said the 7,194-meter bridge linking t...",en
15586,ziyoushijian2,2022-08-19 04:46:29.559130,#Sanya #COVID19 #三亚疫情 #海南疫情防控 #china 据海南省三亚市政府...,zh
15490,fxstreetnewsid,2022-08-19 05:41:47.273113,Harga Baja Menghentikan Tren Naik Empat Pekan ...,in
15827,manshuukankan,2022-08-19 05:41:59.820604,@CCPBotSlayer #china #chineseculture #chineses...,und
...,...,...,...,...
98293,howard_sayles,2023-01-01 02:06:18.220529,https://t.co/yaSPF7ZHEX\nhttps://t.co/6x5Zfeea...,und
97819,BluesyArc284,2023-01-01 02:06:18.291353,2022 was a bad year. Russia attacked Ukraine ...,en
97831,Wh28956221Janet,2023-01-01 02:06:18.829338,@ivan_8848 Would someone please show #Putin to...,en
97671,SueGibb80340378,2023-01-01 02:06:19.514728,@PStyle0ne1 2023 Svět bez #Putin,cs
97609,UKoltko,2023-01-01 02:06:19.631307,@igorlachenkov #RussiaIsATerroristState,und

In [13]:
df_columns["language"].value_counts()

en     52291
und    11318
uk      6448
de      6177
fr      4791
es      4337
it      4047
ru      2898
tr      1307
ja      1235
pt       754
in       696
pl       666
nl       623
ar       560
hi       477
zh       451
fa       425
el       364
fi       333
th       302
vi       259
et       250
ro       247
cs       209
sv       207
ca       184
ur       182
ht       163
da       155
tl       144
iw       130
no       113
ta       111
eu       107
ko       102
bg        94
bn        91
lv        80
gu        76
sl        75
sr        74
te        66
lt        65
kn        63
is        53
ka        52
cy        29
mr        25
hu        24
ml        18
ne        10
pa         8
or         8
am         6
my         6
ps         5
sd         4
si         3
ckb        2
Name: language, dtype: int64

In [14]:
#Leaving only english language tweets
df_columns = df_columns.query('language == "en" or language == "uk"')

In [15]:
df_columns["language"].value_counts()

en    52291
uk     6448
Name: language, dtype: int64

In [16]:
df_columns['created_at'] = pd.to_datetime(df_columns['created_at']).dt.date

/var/folders/gh/sp_gpz4x1q37l7xz154c85gh0000gn/T/ipykernel_28133/1889624915.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_columns['created_at'] = pd.to_datetime(df_columns['created_at']).dt.date

In [17]:
df_columns.sort_values(by=['created_at'])

,username,created_at,tweet,language
15439,Europaetal,2022-08-19,"&lt;When seeking to define #genocide, Lemkin h...",en
15967,joybells49,2022-08-19,'Thought of the Day' (19 August 22) [https://t...,en
15969,BeckyIB,2022-08-19,"Go home, Russians. \n#SlavaUkraini ✨🇺🇦✨ https:...",en
15971,ArvadaRadio,2022-08-19,#StandWithUkraine \n \nhttps://t.co/3JHsLngAJX...,en
15979,resort7983,2022-08-19,🇮🇹#DenisePipitone #Italy #Sicily\n#Missing sin...,en
...,...,...,...,...
98221,ChiliFluff,2023-01-01,Ladies and gentlemen! Behold! The congratulatu...,en
98348,StaVlb,2023-01-01,Київ. 🚨ТРИВОГА - ОБЛАСТЬ\nПРИЧИНА ДРОНИ\nВже в...,uk
98346,DubynaV,2023-01-01,Wellboy - це Робі Вілямс на мінімалках,uk
97992,huidneprodym,2023-01-01,"@FOP_JSS @publeecist Ага, краще дивитися закла...",uk
97657,AEstoletov,2023-01-01,1/3. @ZelenskyyUa ¨And I'll tell you in Russia...,en

In [18]:
df_columns['created_at'].value_counts()

2022-12-25    583
2022-12-08    568
2022-12-05    542
2022-11-09    541
2022-12-27    536
             ...
2022-08-19    331
2022-10-16    289
2023-01-01    146
2022-12-18    138
2022-10-15    118
Name: created_at, Length: 133, dtype: int64

In [19]:
df_columns.to_csv('russia_war_data_sample.csv')